[build]
builder = "nixpacks"
buildCommand = "cd packages/api && npm install && npx prisma generate"

[deploy]
startCommand = "cd packages/api && npx prisma db push --accept-data-loss && node src/index.js"
