[build]
builder = "dockerfile"
dockerfilePath = "packages/api/Dockerfile"

[deploy]
startCommand = "cd packages/api && echo 'Running migrations...' && npx prisma migrate deploy --preview-feature && echo 'Migrations complete' && node src/index.js"
