const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
require('dotenv').config()

const app = express()
app.use(helmet())
app.use(cors({ origin: 'http://localhost:5173', credentials: true }))
app.use(express.json())
app.use('/api/activity', require('./routes/activityLog'))
app.use('/api/users',    require('./routes/users'))
app.use('/api/auth',    require('./routes/auth'))
app.use('/api/groups',  require('./routes/groups'))
app.use('/api/clients', require('./routes/clients'))
app.use('/api/clients', require('./routes/menuItems'))
app.use('/api/clients', require('./routes/analytics'))
app.use('/api/clients', require('./routes/deployment'))

app.get('/health', (req, res) => res.json({ status: 'ok' }))
app.listen(process.env.PORT || 3001, () => console.log('🚀 API running on port 3001'))